services:
  vue-app:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    container_name: vue-app
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app
      - /app/node_modules

# services:
#   vue-app:
#     build:
#       context: .
#       dockerfile: Dockerfile.prd
#     container_name: vue-app-production
#     ports:
#       - '81:80'
