# Use official Node.js LTS image
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

ENV CHOKIDAR_USEPOLLING=true

# Expose the development server port (default: 5173 for Vite)
EXPOSE 5173


# Start the development server
CMD ["bash", "-c", "npm install && npm run dev"]
